### PR TITLE
Switched Frontends go Gradio

### PR DESCRIPTION
**Pull request by aleneum**
I refactored the frontends to Gradio and added some functionality on the way. They are started now with

```
poetry poe gen
poetry poe qa
```

The reload function from `gradio` currently does not play nice with the `Bridge` transport. It seems like connections and/or object instance are not correctly re-initialized when the GUI is reloaded. So you probably need to close and reopen the browser window and the app itself from time to time. When decoupling services and frontend, this issue should also vanish. But maybe there is a better way to configure the gradio app anyway.

Some screenshots:

Screenshot 2023-11-13 at 10 49 13
Screenshot 2023-11-13 at 10 50 21

### CODE REVIEW

**Review by Depo14 — APPROVED** [review]
The qa part is running for me, even if it seems to me that the whole application has become much slower and the output of the answer is worse. But the model response is not due to the GUI :)

**Review by Ashtonville — APPROVED** [review]
It runs without problems. Although it does seem like the it takes ages to run because of gradio. Does that stem from the problem you mentioned regarding the interaction between gradio and transport?

**Comment by aleneum** [comment]
Gradio should not have a big impact on performance. As you know the quality depends on many factors (e.g. chunk size, overlap, ...). Also do not underestimate the role of the prompt and its formatting! I guess my next PR will be to split config parameters for `gen` and `qa` so that both of you can set them independently.

**Comment by aleneum** [comment]
> The qa part is running for me, even if it seems to me that the whole application has become much slower and the output of the answer is worse. But the model response is not due to the GUI :)

You could try to create a "no auto" pytest where you address the `qa_service` directly and check whether that is way faster.

**Comment by aleneum** [comment]
Well, I guess I found one problem. Temperature is set to `max_new_tokens`.

**Comment by aleneum** [comment]
Well, I guess I found one problem. Temperature is set to `max_new_tokens`.

**Pull request merged**
